name: test

permissions: {}

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
        with:
          enable-cache: false

      - name: Run cpu info
        run: |
          cat > test.py <<'PY'
          import platform
          from pprint import pprint
          import cpuinfo

          print(platform.machine())
          print(platform.processor())
          pprint(cpuinfo.get_cpu_info())
          PY

          uv venv .venv --python 3.14
          source .venv/bin/activate
          uv pip install py-cpuinfo2

          python test.py
