name: "Some tests"

on:
  push:
  workflow_dispatch:

jobs:
  with_mimalloc:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-26.04-arm
          - macos-latest
          - macos-26-intel
          - windows-latest
          - windows-11-vs2026-arm

    steps:
      - name: "Install uv"
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false

      - uses: dtolnay/rust-toolchain@stable # zizmor: ignore[unpinned-uses]

      - name: "Run toml_rs playwright test"
        shell: bash
        run: |
          uv venv .venv --python 3.13

          if [[ "${{ matrix.os }}" == windows-* ]]; then
            PYTHON="$PWD/.venv/Scripts/python.exe"
          else
            PYTHON="$PWD/.venv/bin/python"
          fi

          uv pip install --python "$PYTHON" maturin playwright

          git clone --branch vbbb https://github.com/lava-sh/toml-rs.git toml_rs_repo
          cd toml_rs_repo

          "$PYTHON" -m maturin build --out wheel --features mimalloc

          uv pip install --python "$PYTHON" wheel/*.whl

          cd ..

          cat > issues_229.py <<'PY'
          import asyncio
          from playwright.async_api import async_playwright
          import toml_rs

          async def main() -> None:
              playwright = await async_playwright().start()
              await playwright.stop()

          if __name__ == "__main__":
              asyncio.run(main())
          PY

          "$PYTHON" issues_229.py
