name: "Some tests"

on:
  push:
  workflow_dispatch:

jobs:
#  from_pypi:
#    runs-on: ${{ matrix.runner }}
#    strategy:
#      fail-fast: false
#      matrix:
#        runner: [
#          "ubuntu-latest",
#          "ubuntu-26.04-arm",
#          "macos-latest",
#          "macos-26-intel",
#          "windows-latest",
#          "windows-11-vs2026-arm",
#        ]
#
#    steps:
#      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
#        with:
#          persist-credentials: false
#
#      - name: "Install uv"
#        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
#        with:
#          enable-cache: false
#
#      - uses: dtolnay/rust-toolchain@stable # zizmor: ignore[unpinned-uses]
#
#      - shell: bash
#        run: |
#          ls
#
#          uv venv .venv --python 3.13
#
#          if [[ "${{ matrix.runner }}" == windows-* ]]; then
#            export UV_LINK_MODE=copy
#            source .venv/Scripts/activate
#          else
#            source .venv/bin/activate
#          fi
#
#          uv pip install toml-rs playwright
#
#          python issue_229.py

  from_src_without_mimalloc:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [
          "ubuntu-latest",
          "ubuntu-26.04-arm",
          "macos-latest",
          "macos-26-intel",
          "windows-latest",
          "windows-11-vs2026-arm",
        ]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Install uv"
        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
        with:
          enable-cache: false

      - uses: dtolnay/rust-toolchain@stable # zizmor: ignore[unpinned-uses]

      - shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          uv venv .venv --python 3.13

          if [[ "${{ matrix.runner }}" == windows-* ]]; then
            export UV_LINK_MODE=copy
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          
          uv pip install playwright maturin
          
          gh repo clone lava-sh/toml-rs _toml-rs
          cd _toml-rs
          
          maturin build --out wheel
          uv pip install wheel/*.whl
          
          cd ..

          python issue_229.py

  from_src_with_mimalloc:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [
          "ubuntu-latest",
          "ubuntu-26.04-arm",
          "macos-latest",
          "macos-26-intel",
          "windows-latest",
          "windows-11-vs2026-arm",
        ]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Install uv"
        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
        with:
          enable-cache: false

      - uses: dtolnay/rust-toolchain@stable # zizmor: ignore[unpinned-uses]

      - shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          uv venv .venv --python 3.13

          if [[ "${{ matrix.runner }}" == windows-* ]]; then
            export UV_LINK_MODE=copy
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          
          uv pip install playwright maturin
          
          gh repo clone lava-sh/toml-rs _toml-rs -- --branch chirizxc-patch-1
          cd _toml-rs
          
          maturin build --out wheel
          uv pip install wheel/*.whl
          
          cd ..

          python issue_229.py